accounts/urls.py
from django.urls import re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^signup/$', views.signup_view, name="signup"),
    re_path(r'^login/$', views.login_view, name="login"),
    re_path(r'^logout/$', views.logout_view, name="logout"),
]

book_quote/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.homepage, name="homepage"),
    re_path(r'^select2/', include('django_select2.urls')),
    re_path(r'^quotes/', include('quotes.urls')),
    re_path(r'^accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/urls.py
from django.contrib import admin
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.quotes_view, name="quotes"), 
    re_path(r'^scores$', views.scores_view, name="scores"),
    re_path(r'^create-quote', views.create_quote_view, name="create_quote"),
    re_path(r'^create-book', views.create_book_view, name="create_book"),
    re_path(r'^create-author', views.create_author_view, name="create_author"),
    re_path(r'^upvote', views.upvote_view, name="upvote_quote")
]

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>

    {% block head %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container-xxl">
            <!-- brand title -->
            <a href="{% url 'homepage' %}" class="navbar-brand">
                <span class="fw-bold">
                    BookQuest
                </span>
            </a>

            <!-- toggle button for mobile nav -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#main-nav" aria-controls="main-nav" aria-expanded="false"
            aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- navbar links -->
            <div class="collapse navbar-collapse justify-content-end align-center"
            id="main-nav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a 
                            class="nav-link {% if request.path == '/quotes/' %}active{% endif %}" 
                            href="{% url 'quotes' %}">
                            Play
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                            class="nav-link {% if request.path == '/quotes/scores' %}active{% endif %}"
                            href="{% url 'scores' %}">
                            Scores
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                            class="nav-link {% if request.path == '/quotes/create-quote' %}active{% endif %}"
                            href="{% url 'create_quote' %}">
                            Create
                        </a>
                    </li>
                    <!-- User section -->
                    {% if user.is_authenticated %}
                    <li class="nav-item ms-2">
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-secondary" type="submit">Logout</button>
                        </form>
                    </li>
                    <li class="ms-2 navbar-brand">
                        <span class="fw-bold">
                            {{ user.username }}
                        </span>
                    </li>
                    {% else %}
                    <li class="nav-item ms-2">
                        <form class="login-link" action="{% url 'accounts:login' %}" method="get">
                            {% csrf_token %}
                            <button class="btn btn-secondary" type="submit">Login</button>
                        </form>
                    </li>
                    <li class="nav-item ms-2">
                        <form class="signup-link" action="{% url 'accounts:signup' %}" method="get">
                            {% csrf_token %}
                            <button class="btn btn-secondary" type="submit">Signup</button>
                        </form>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="row text-center pt-5">
    <h1>Welcome to BookQuest!</h1>
</div>

<div class="row text-center pt-5">
    <p>Select "Play" to guess books from quotes!</p>
</div>
{% endblock %}